# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ""
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, "README.rst")
if os.path.exists(readme_path):
    with open(readme_path, "rb") as stream:
        readme = stream.read().decode("utf8")


setup(
    long_description=readme,
    name="python-srtm",
    version="0.3.0",
    python_requires="==3.*,>=3.6.0",
    project_urls={"repository": "https://github.com/adamcharnock/python-srtm"},
    author="Adam Charnock",
    author_email="adam@adamcharnock.com",
    license="MIT",
    keywords="nasa geospatial altitude elevation-profile",
    packages=["srtm"],
    package_dir={"": "."},
    package_data={},
    install_requires=[],
    extras_require={
        "dev": ["black==19.*,>=19.10.0", "dephell==0.*,>=0.8.2", "pytest==5.*,>=5.4.1"]
    },
)
